<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-RF7CNPCF" failures="12" tests="27" name="Test" time="0.178" errors="0" timestamp="2022-06-04T18:21:20 IST">
  <testcase classname="ListenDemo.Sample" name="test1" time="0.005"/>
  <testcase classname="ListenDemo.Sample" name="test2" time="0.004">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at ListenDemo.Sample.test2(Sample.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="ListenDemo.Sample" name="test3" time="0.009"/>
  <testcase classname="ListenDemo.Sample" name="test4" time="0.002">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at ListenDemo.Sample.test4(Sample.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase classname="Direct_Test.NewTest" name="suhas" time="0.001"/>
  <testcase classname="package_Xml.Demo2" name="method3" time="0.003"/>
  <testcase classname="package_Xml.Demo2" name="method4" time="0.001"/>
  <testcase classname="package_Xml.Demo2" name="method5" time="0.002"/>
  <testcase classname="Assertion.Hard_Assert" name="show1" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [sanket] but found [suhas]">
      <![CDATA[java.lang.AssertionError: expected [sanket] but found [suhas]
at Assertion.Hard_Assert.show1(Hard_Assert.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- show1 -->
  <testcase classname="Assertion.Hard_Assert" name="show2" time="0.002"/>
  <testcase classname="Assertion.Hard_Assert" name="show3" time="0.001"/>
  <testcase classname="Assertion.Hard_Assert" name="show4" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at Assertion.Hard_Assert.show4(Hard_Assert.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- show4 -->
  <testcase classname="Assertion.Hard_Assert" name="show5" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Assertion.Hard_Assert.show5(Hard_Assert.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- show5 -->
  <testcase classname="Assertion.Hard_Assert" name="show6" time="0.0"/>
  <testcase classname="Assertion.Hard_Assert" name="show7" time="0.001"/>
  <testcase classname="Assertion.Hard_Assert" name="show8" time="0.001">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at Assertion.Hard_Assert.show8(Hard_Assert.java:65)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- show8 -->
  <testcase classname="package_Xml.Demo_1" name="method1" time="0.002">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at package_Xml.Demo_1.method1(Demo_1.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- method1 -->
  <testcase classname="package_Xml.Demo_1" name="method2" time="0.003"/>
  <testcase classname="Assertion.Soft_Assertion" name="display1" time="0.002">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [7] but found [5]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [7] but found [5]
at Assertion.Soft_Assertion.display1(Soft_Assertion.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- display1 -->
  <testcase classname="Assertion.Soft_Assertion" name="display2" time="0.002">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [7] but found [5]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [7] but found [5]
at Assertion.Soft_Assertion.display2(Soft_Assertion.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- display2 -->
  <testcase classname="Assertion.Soft_Assertion" name="display3" time="0.002">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [7] but found [5]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [7] but found [5]
at Assertion.Soft_Assertion.display3(Soft_Assertion.java:34)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- display3 -->
  <testcase classname="Assertion.Soft_Assertion" name="display4" time="0.002">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [7] but found [5],
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [7] but found [5],
expected [false] but found [true]
at Assertion.Soft_Assertion.display4(Soft_Assertion.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- display4 -->
  <testcase classname="Test.Example1" name="Data2" time="0.001"/>
  <testcase classname="Test.Example1" name="Data1" time="0.001"/>
  <testcase classname="Assertion.Soft_AssertEX2" name="patil1" time="0.0"/>
  <testcase classname="Assertion.Soft_AssertEX2" name="patil2" time="0.002">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at Assertion.Soft_AssertEX2.patil2(Soft_AssertEX2.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- patil2 -->
  <testcase classname="Assertion.Soft_AssertEX2" name="patil3" time="0.001"/>
</testsuite> <!-- Test -->
